name: Despliegue

on:

  push:
    branches: [ "main" , "Dev"]


  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  
  SAST:
    
    name: Analyze (${{ matrix.language }})
    
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: javascript-typescript
          build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
         languages: ${{ matrix.language }}
         build-mode: ${{ matrix.build-mode }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"    

  build:
    runs-on: ubuntu-latest
    needs: SAST
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Configuracion Node.js
        uses: actions/setup-node@v3
        with:
         node-version: "20"  
      
      - name: Comprobación del cumplimiento de la licencia
        uses: mikaelvesavuori/license-compliance-action@v1
        with:
           allow_licenses: "https://www.mockachino.com/{{MIT;ISC;0BSD;BSD-2-Clause;BSD-3-Clause;Apache-2.0}}/licenses"
           nested_field: "licenseString"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Analisis de desempeño Lighthouse 
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://jamesromero20.github.io/login/
     
      - name: Ejecutar prueba de carga Apache Benchmark
        run: |
          ab -n 100 -c 10 https://jamesromero20.github.io/login/

      - name: Escaneo ZAP
        uses: zaproxy/action-full-scan@v0.12.0
        with:
         target: "https://jamesromero20.github.io/login/"
        env:
          JAVA_OPTS: "-Xmx512m"
      
      - name: Despliegue a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

